### PR TITLE
Final Updates

### PR DESCRIPTION
**Pull request by Gianna-Mantegna**
Should be completed until we come back for redesign.

### CODE REVIEW

**Comment by kylindreagan** [comment]
The calculator doesn't work if loan term isn't an integer but there seems to be no check in place for that. Otherwise looks good.
image

**Comment by Gianna-Mantegna** [comment]
Should be fine now. It had a really strange logic error in the check Fields function.

**Comment by Gus4812** [comment]
Im not sure if I downloaded the correct one however, I was seeing if loan term works if its a float and it crashed. Also I noticed one test case for the home price that if no down payment, and no closing cost it will return a custom result output on the original calculator "given that there are no down payment or closing costs,..." but this may be more related to design. 
Screenshot 2024-11-10 at 6 15 20 PM

Other than that, everything looks good!

**Review by kylindreagan — APPROVED** [review]
The calculate down payment % has an empty line above it but everything looks in order otherwise

**Pull request merged**
