### PR TITLE
Main form

### PR DESCRIPTION
**Pull request by Gianna-Mantegna**
Main form completed.
Buttons will not run properly until connected to another form of the appropriate name.
Includes blank forms for Amortization Calculator, Currency Converter, and Mortgage Calculator.
(Only button for the above forms will open a form)

Form names used (up for change):
CurrencyConverter()
MortgageCalculator()
AmortizationCalculator()
RentVsBuyCalculator()
HouseAffordabilityCalculator()
RetirementCalculator()
AutoLoanCalculator()
InterestCalculator()
RentCalculator()
RefinanceCalculator()
RothIRACalculator()
DownPaymentCalculator()

### CODE REVIEW

**Comment by kylindreagan** [comment]
This won't let you merge until the checks pass, says there are conflictions in main with all the lines like this : private void rentVsBuyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentVsBuyButtonMouseClicked
        new RentVsBuyCalculator().setVisible(true);
    }//GEN-LAST:event_rentVsBuyButtonMouseClicked.
Not sure why that is but if you want to push now you need to fix these. You do not need a new pull request though, until it gets merged it will keep up with changes in this branch.

**Comment by Gianna-Mantegna** [comment]
Thanks, I didn't realize it wouldn't pull. I know what the problem is.

**Comment by Gianna-Mantegna** [comment]
Added blank forms for all the calculators with the aforementioned names.

**Review by kylindreagan — APPROVED** [review]
All looks good!

**Pull request merged**
