### PR TITLE
Yen fix

### PR DESCRIPTION
**Pull request by kylindreagan**
May be last currency update until we finalize designs and tests and stuff

### CODE REVIEW

**Review by Gianna-Mantegna — COMMENTED** [review]
I'm not sure the fix you made did what you wanted it to do. I'm not sure why I'm receiving this error from the program 
image

**Comment by kylindreagan** [comment]
I will make the error more specific but currencies like Japanese Yen, Chilean Pesos, and South Korean Won do not use cents.

**Comment by Gianna-Mantegna** [comment]
Gotcha ok!

**Review by Gianna-Mantegna — APPROVED** [review]
No notes, looks good

**Pull request merged**
