### PR TITLE
Roth ira

### PR DESCRIPTION
**Pull request by kylindreagan**
Maybe finished another calculator.

### CODE REVIEW

**Review by Gianna-Mantegna — COMMENTED** [review]
I haven't thoroughly gone through all the functions, but it broke when I clicked the maximize button then calculate. Something about a Number Format Exception Error

**Comment by kylindreagan** [comment]
My bad twas a typo

**Comment by Gianna-Mantegna** [comment]
I found an error when hitting clear current while having the contribution maximized. The Expected rate of return lights up red? 
Also the calculations for total interest in the Roth IRA and Taxable account seem off.

**Comment by kylindreagan** [comment]
I think I fixed the contribution thing but I couldn't replicate ERR becoming red. I also just never checked interest apparently because I wasn't calculating it right at all.

**Review by Gianna-Mantegna — APPROVED** [review]
slay

**Pull request merged**
